apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: g6hakxtnt-go 
  janus-idp.io/tekton: g6hakxtnt-go
  backstage.io/kubernetes-id: g6hakxtnt-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g6hakxtnt-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  